version: "3.9"

services:
  homebasket_backend:
    build: ./homebasket_backend
    container_name: homebasket_backend_app
    environment:
      - DJANGO_SETTINGS_MODULE=homebasket.settings
    volumes:
      - ./homebasket_backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./homebasket_backend/.env
    depends_on:
      - db

  homebasket_frontend:
    build: ./homebasket_frontend
    container_name: homebasket_frontend_app
    ports:
      - "80:80"

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: homebasket
      POSTGRES_USER: sachin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
