# Generated by Django 5.2.5 on 2025-08-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('Fruits & Vegetables', 'Fruits & Vegetables'), ('Dairy & Eggs', 'Dairy & Eggs'), ('Oils, Spices & Condiments', 'Oils, Spices & Condiments'), ('Household & Cleaning', 'Household & Cleaning')], max_length=50)),
            ],
        ),
    ]
