# Generated by Django 5.2.5 on 2025-09-16 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryListBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('purchased', models.BooleanField(default=False)),
                ('backup_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_backups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
