# Generated by Django 5.2.5 on 2025-09-16 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_grocerylistbackup_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='grocerylistbackup',
            table='grocery_list_backup',
        ),
    ]
