# Generated by Django 5.2.5 on 2025-09-16 07:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_grocerylist_purchased_alter_grocerylist_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
