# Generated by Django 5.2.5 on 2025-09-16 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_grocerylist_created_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='grocerylist',
            table='grocery_list',
        ),
    ]
