# Generated by Django 5.2.5 on 2025-09-16 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_grocerylist_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grocerylist',
            old_name='name',
            new_name='item_name',
        ),
    ]
